// flow-typed signature: e6de8592962d92e859b61a4bcae8662a
// flow-typed version: <<STUB>>/@chakra-ui/icons_v^1.0.3/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chakra-ui/icons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chakra-ui/icons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chakra-ui/icons/dist/cjs/Add' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowBack' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowForward' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowLeft' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowRight' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowUp' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ArrowUpDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/AtSign' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Attachment' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Bell' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Calendar' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Chat' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Check' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/CheckCircle' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ChevronDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ChevronLeft' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ChevronRight' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ChevronUp' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Close' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Copy' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Delete' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Download' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/DragHandle' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Edit' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Email' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ExternalLink' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Hamburger' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/icons.stories' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Info' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/InfoOutline' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Link' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Lock' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Minus' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Moon' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/NotAllowed' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Phone' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/PlusSquare' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Question' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/QuestionOutline' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Repeat' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/RepeatClock' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Search' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Search2' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Settings' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/SmallAdd' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/SmallClose' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Spinner' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Star' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Sun' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Time' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/TriangleDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/TriangleUp' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Unlock' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/UpDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/View' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/ViewOff' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/Warning' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/cjs/WarningTwo' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Add' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowBack' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowForward' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowLeft' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowRight' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowUp' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ArrowUpDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/AtSign' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Attachment' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Bell' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Calendar' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Chat' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Check' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/CheckCircle' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ChevronDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ChevronLeft' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ChevronRight' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ChevronUp' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Close' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Copy' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Delete' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Download' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/DragHandle' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Edit' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Email' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ExternalLink' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Hamburger' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/icons.stories' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Info' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/InfoOutline' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Link' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Lock' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Minus' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Moon' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/NotAllowed' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Phone' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/PlusSquare' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Question' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/QuestionOutline' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Repeat' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/RepeatClock' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Search' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Search2' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Settings' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/SmallAdd' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/SmallClose' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Spinner' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Star' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Sun' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Time' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/TriangleDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/TriangleUp' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Unlock' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/UpDown' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/View' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/ViewOff' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/Warning' {
  declare module.exports: any;
}

declare module '@chakra-ui/icons/dist/esm/WarningTwo' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chakra-ui/icons/dist/cjs/Add.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Add'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowBack.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowBack'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowDown'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowForward.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowForward'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowLeft.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowLeft'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowRight.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowRight'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowUp.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowUp'>;
}
declare module '@chakra-ui/icons/dist/cjs/ArrowUpDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ArrowUpDown'>;
}
declare module '@chakra-ui/icons/dist/cjs/AtSign.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/AtSign'>;
}
declare module '@chakra-ui/icons/dist/cjs/Attachment.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Attachment'>;
}
declare module '@chakra-ui/icons/dist/cjs/Bell.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Bell'>;
}
declare module '@chakra-ui/icons/dist/cjs/Calendar.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Calendar'>;
}
declare module '@chakra-ui/icons/dist/cjs/Chat.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Chat'>;
}
declare module '@chakra-ui/icons/dist/cjs/Check.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Check'>;
}
declare module '@chakra-ui/icons/dist/cjs/CheckCircle.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/CheckCircle'>;
}
declare module '@chakra-ui/icons/dist/cjs/ChevronDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ChevronDown'>;
}
declare module '@chakra-ui/icons/dist/cjs/ChevronLeft.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ChevronLeft'>;
}
declare module '@chakra-ui/icons/dist/cjs/ChevronRight.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ChevronRight'>;
}
declare module '@chakra-ui/icons/dist/cjs/ChevronUp.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ChevronUp'>;
}
declare module '@chakra-ui/icons/dist/cjs/Close.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Close'>;
}
declare module '@chakra-ui/icons/dist/cjs/Copy.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Copy'>;
}
declare module '@chakra-ui/icons/dist/cjs/Delete.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Delete'>;
}
declare module '@chakra-ui/icons/dist/cjs/Download.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Download'>;
}
declare module '@chakra-ui/icons/dist/cjs/DragHandle.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/DragHandle'>;
}
declare module '@chakra-ui/icons/dist/cjs/Edit.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Edit'>;
}
declare module '@chakra-ui/icons/dist/cjs/Email.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Email'>;
}
declare module '@chakra-ui/icons/dist/cjs/ExternalLink.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ExternalLink'>;
}
declare module '@chakra-ui/icons/dist/cjs/Hamburger.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Hamburger'>;
}
declare module '@chakra-ui/icons/dist/cjs/icons.stories.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/icons.stories'>;
}
declare module '@chakra-ui/icons/dist/cjs/index' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs'>;
}
declare module '@chakra-ui/icons/dist/cjs/index.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs'>;
}
declare module '@chakra-ui/icons/dist/cjs/Info.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Info'>;
}
declare module '@chakra-ui/icons/dist/cjs/InfoOutline.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/InfoOutline'>;
}
declare module '@chakra-ui/icons/dist/cjs/Link.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Link'>;
}
declare module '@chakra-ui/icons/dist/cjs/Lock.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Lock'>;
}
declare module '@chakra-ui/icons/dist/cjs/Minus.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Minus'>;
}
declare module '@chakra-ui/icons/dist/cjs/Moon.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Moon'>;
}
declare module '@chakra-ui/icons/dist/cjs/NotAllowed.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/NotAllowed'>;
}
declare module '@chakra-ui/icons/dist/cjs/Phone.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Phone'>;
}
declare module '@chakra-ui/icons/dist/cjs/PlusSquare.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/PlusSquare'>;
}
declare module '@chakra-ui/icons/dist/cjs/Question.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Question'>;
}
declare module '@chakra-ui/icons/dist/cjs/QuestionOutline.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/QuestionOutline'>;
}
declare module '@chakra-ui/icons/dist/cjs/Repeat.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Repeat'>;
}
declare module '@chakra-ui/icons/dist/cjs/RepeatClock.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/RepeatClock'>;
}
declare module '@chakra-ui/icons/dist/cjs/Search.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Search'>;
}
declare module '@chakra-ui/icons/dist/cjs/Search2.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Search2'>;
}
declare module '@chakra-ui/icons/dist/cjs/Settings.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Settings'>;
}
declare module '@chakra-ui/icons/dist/cjs/SmallAdd.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/SmallAdd'>;
}
declare module '@chakra-ui/icons/dist/cjs/SmallClose.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/SmallClose'>;
}
declare module '@chakra-ui/icons/dist/cjs/Spinner.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Spinner'>;
}
declare module '@chakra-ui/icons/dist/cjs/Star.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Star'>;
}
declare module '@chakra-ui/icons/dist/cjs/Sun.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Sun'>;
}
declare module '@chakra-ui/icons/dist/cjs/Time.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Time'>;
}
declare module '@chakra-ui/icons/dist/cjs/TriangleDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/TriangleDown'>;
}
declare module '@chakra-ui/icons/dist/cjs/TriangleUp.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/TriangleUp'>;
}
declare module '@chakra-ui/icons/dist/cjs/Unlock.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Unlock'>;
}
declare module '@chakra-ui/icons/dist/cjs/UpDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/UpDown'>;
}
declare module '@chakra-ui/icons/dist/cjs/View.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/View'>;
}
declare module '@chakra-ui/icons/dist/cjs/ViewOff.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/ViewOff'>;
}
declare module '@chakra-ui/icons/dist/cjs/Warning.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/Warning'>;
}
declare module '@chakra-ui/icons/dist/cjs/WarningTwo.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/cjs/WarningTwo'>;
}
declare module '@chakra-ui/icons/dist/esm/Add.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Add'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowBack.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowBack'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowDown'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowForward.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowForward'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowLeft.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowLeft'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowRight.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowRight'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowUp.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowUp'>;
}
declare module '@chakra-ui/icons/dist/esm/ArrowUpDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ArrowUpDown'>;
}
declare module '@chakra-ui/icons/dist/esm/AtSign.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/AtSign'>;
}
declare module '@chakra-ui/icons/dist/esm/Attachment.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Attachment'>;
}
declare module '@chakra-ui/icons/dist/esm/Bell.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Bell'>;
}
declare module '@chakra-ui/icons/dist/esm/Calendar.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Calendar'>;
}
declare module '@chakra-ui/icons/dist/esm/Chat.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Chat'>;
}
declare module '@chakra-ui/icons/dist/esm/Check.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Check'>;
}
declare module '@chakra-ui/icons/dist/esm/CheckCircle.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/CheckCircle'>;
}
declare module '@chakra-ui/icons/dist/esm/ChevronDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ChevronDown'>;
}
declare module '@chakra-ui/icons/dist/esm/ChevronLeft.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ChevronLeft'>;
}
declare module '@chakra-ui/icons/dist/esm/ChevronRight.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ChevronRight'>;
}
declare module '@chakra-ui/icons/dist/esm/ChevronUp.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ChevronUp'>;
}
declare module '@chakra-ui/icons/dist/esm/Close.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Close'>;
}
declare module '@chakra-ui/icons/dist/esm/Copy.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Copy'>;
}
declare module '@chakra-ui/icons/dist/esm/Delete.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Delete'>;
}
declare module '@chakra-ui/icons/dist/esm/Download.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Download'>;
}
declare module '@chakra-ui/icons/dist/esm/DragHandle.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/DragHandle'>;
}
declare module '@chakra-ui/icons/dist/esm/Edit.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Edit'>;
}
declare module '@chakra-ui/icons/dist/esm/Email.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Email'>;
}
declare module '@chakra-ui/icons/dist/esm/ExternalLink.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ExternalLink'>;
}
declare module '@chakra-ui/icons/dist/esm/Hamburger.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Hamburger'>;
}
declare module '@chakra-ui/icons/dist/esm/icons.stories.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/icons.stories'>;
}
declare module '@chakra-ui/icons/dist/esm/index' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm'>;
}
declare module '@chakra-ui/icons/dist/esm/index.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm'>;
}
declare module '@chakra-ui/icons/dist/esm/Info.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Info'>;
}
declare module '@chakra-ui/icons/dist/esm/InfoOutline.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/InfoOutline'>;
}
declare module '@chakra-ui/icons/dist/esm/Link.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Link'>;
}
declare module '@chakra-ui/icons/dist/esm/Lock.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Lock'>;
}
declare module '@chakra-ui/icons/dist/esm/Minus.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Minus'>;
}
declare module '@chakra-ui/icons/dist/esm/Moon.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Moon'>;
}
declare module '@chakra-ui/icons/dist/esm/NotAllowed.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/NotAllowed'>;
}
declare module '@chakra-ui/icons/dist/esm/Phone.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Phone'>;
}
declare module '@chakra-ui/icons/dist/esm/PlusSquare.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/PlusSquare'>;
}
declare module '@chakra-ui/icons/dist/esm/Question.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Question'>;
}
declare module '@chakra-ui/icons/dist/esm/QuestionOutline.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/QuestionOutline'>;
}
declare module '@chakra-ui/icons/dist/esm/Repeat.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Repeat'>;
}
declare module '@chakra-ui/icons/dist/esm/RepeatClock.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/RepeatClock'>;
}
declare module '@chakra-ui/icons/dist/esm/Search.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Search'>;
}
declare module '@chakra-ui/icons/dist/esm/Search2.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Search2'>;
}
declare module '@chakra-ui/icons/dist/esm/Settings.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Settings'>;
}
declare module '@chakra-ui/icons/dist/esm/SmallAdd.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/SmallAdd'>;
}
declare module '@chakra-ui/icons/dist/esm/SmallClose.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/SmallClose'>;
}
declare module '@chakra-ui/icons/dist/esm/Spinner.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Spinner'>;
}
declare module '@chakra-ui/icons/dist/esm/Star.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Star'>;
}
declare module '@chakra-ui/icons/dist/esm/Sun.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Sun'>;
}
declare module '@chakra-ui/icons/dist/esm/Time.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Time'>;
}
declare module '@chakra-ui/icons/dist/esm/TriangleDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/TriangleDown'>;
}
declare module '@chakra-ui/icons/dist/esm/TriangleUp.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/TriangleUp'>;
}
declare module '@chakra-ui/icons/dist/esm/Unlock.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Unlock'>;
}
declare module '@chakra-ui/icons/dist/esm/UpDown.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/UpDown'>;
}
declare module '@chakra-ui/icons/dist/esm/View.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/View'>;
}
declare module '@chakra-ui/icons/dist/esm/ViewOff.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/ViewOff'>;
}
declare module '@chakra-ui/icons/dist/esm/Warning.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/Warning'>;
}
declare module '@chakra-ui/icons/dist/esm/WarningTwo.js' {
  declare module.exports: $Exports<'@chakra-ui/icons/dist/esm/WarningTwo'>;
}
