// flow-typed signature: 5b06847efa0c445dd101bea911618693
// flow-typed version: <<STUB>>/@chakra-ui/react_v^1.1.5/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@chakra-ui/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@chakra-ui/react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@chakra-ui/react/dist/cjs/chakra-provider' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs/extend-theme' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs/theme-extensions' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-color-scheme' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-props' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-size' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-variant' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/chakra-provider' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/extend-theme' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/theme-extensions' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-color-scheme' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-props' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-size' {
  declare module.exports: any;
}

declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-variant' {
  declare module.exports: any;
}

// Filename aliases
declare module '@chakra-ui/react/dist/cjs/chakra-provider.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/chakra-provider'>;
}
declare module '@chakra-ui/react/dist/cjs/extend-theme.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/extend-theme'>;
}
declare module '@chakra-ui/react/dist/cjs/index' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs'>;
}
declare module '@chakra-ui/react/dist/cjs/index.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs'>;
}
declare module '@chakra-ui/react/dist/cjs/theme-extensions/index' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/theme-extensions'>;
}
declare module '@chakra-ui/react/dist/cjs/theme-extensions/index.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/theme-extensions'>;
}
declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-color-scheme.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/theme-extensions/with-default-color-scheme'>;
}
declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-props.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/theme-extensions/with-default-props'>;
}
declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-size.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/theme-extensions/with-default-size'>;
}
declare module '@chakra-ui/react/dist/cjs/theme-extensions/with-default-variant.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/cjs/theme-extensions/with-default-variant'>;
}
declare module '@chakra-ui/react/dist/esm/chakra-provider.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/chakra-provider'>;
}
declare module '@chakra-ui/react/dist/esm/extend-theme.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/extend-theme'>;
}
declare module '@chakra-ui/react/dist/esm/index' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm'>;
}
declare module '@chakra-ui/react/dist/esm/index.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm'>;
}
declare module '@chakra-ui/react/dist/esm/theme-extensions/index' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/theme-extensions'>;
}
declare module '@chakra-ui/react/dist/esm/theme-extensions/index.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/theme-extensions'>;
}
declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-color-scheme.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/theme-extensions/with-default-color-scheme'>;
}
declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-props.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/theme-extensions/with-default-props'>;
}
declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-size.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/theme-extensions/with-default-size'>;
}
declare module '@chakra-ui/react/dist/esm/theme-extensions/with-default-variant.js' {
  declare module.exports: $Exports<'@chakra-ui/react/dist/esm/theme-extensions/with-default-variant'>;
}
