nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs

npmScopes:
  frinxio:
    npmRegistryServer: 'https://npm.pkg.github.com/'
    npmAuthToken: ${PRIVATE_GH_TOKEN}
  frinx:
    npmAlwaysAuth: true
    npmPublishRegistry: 'https://registry.npmjs.org/'
    npmAuthToken: ${PRIVATE_NPM_TOKEN}
