nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.4.cjs

npmScopes:
  frinxio:
    npmRegistryServer: 'https://npm.pkg.github.com/'
  frinx:
    npmAlwaysAuth: true
    npmPublishRegistry: 'https://registry.npmjs.org/'
