nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.2.0.cjs

npmScopes:
  frinxio:
    npmRegistryServer: 'https://npm.pkg.github.com/'
  frinx:
    npmAlwaysAuth: true

  npmRegistries:
  'https://npm.pkg.github.com':
    npmAuthToken: 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
