version: '3.8'
services:
  postgres-local:
    image: postgres:12-alpine
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker-volumes/postgres:/docker-entrypoint-initdb.d
