// flow-typed signature: cfddb83944bfeadfe2d341d64b635186
// flow-typed version: <<STUB>>/chakra-paginator_v^0.6.3/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'chakra-paginator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'chakra-paginator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'chakra-paginator/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'chakra-paginator/dist/index' {
  declare module.exports: $Exports<'chakra-paginator/dist'>;
}
declare module 'chakra-paginator/dist/index.js' {
  declare module.exports: $Exports<'chakra-paginator/dist'>;
}
