// flow-typed signature: 71609294af04278e2f4dd16666800280
// flow-typed version: <<STUB>>/dagre-d3_v^0.6.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'dagre-d3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'dagre-d3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'dagre-d3/dist/dagre-d3.core' {
  declare module.exports: any;
}

declare module 'dagre-d3/dist/dagre-d3.core.min' {
  declare module.exports: any;
}

declare module 'dagre-d3/dist/dagre-d3' {
  declare module.exports: any;
}

declare module 'dagre-d3/dist/dagre-d3.min' {
  declare module.exports: any;
}

declare module 'dagre-d3/dist/demo/demo' {
  declare module.exports: any;
}

declare module 'dagre-d3/dist/demo/tipsy' {
  declare module.exports: any;
}

declare module 'dagre-d3/karma.conf' {
  declare module.exports: any;
}

declare module 'dagre-d3/karma.core.conf' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/arrows' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/create-clusters' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/create-edge-labels' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/create-edge-paths' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/create-nodes' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/d3' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/dagre' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/graphlib' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect/intersect-circle' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect/intersect-ellipse' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect/intersect-line' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect/intersect-node' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect/intersect-polygon' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/intersect/intersect-rect' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/label/add-html-label' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/label/add-label' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/label/add-svg-label' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/label/add-text-label' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/lodash' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/position-clusters' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/position-edge-labels' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/position-nodes' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/render' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/shapes' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/util' {
  declare module.exports: any;
}

declare module 'dagre-d3/lib/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'dagre-d3/dist/dagre-d3.core.js' {
  declare module.exports: $Exports<'dagre-d3/dist/dagre-d3.core'>;
}
declare module 'dagre-d3/dist/dagre-d3.core.min.js' {
  declare module.exports: $Exports<'dagre-d3/dist/dagre-d3.core.min'>;
}
declare module 'dagre-d3/dist/dagre-d3.js' {
  declare module.exports: $Exports<'dagre-d3/dist/dagre-d3'>;
}
declare module 'dagre-d3/dist/dagre-d3.min.js' {
  declare module.exports: $Exports<'dagre-d3/dist/dagre-d3.min'>;
}
declare module 'dagre-d3/dist/demo/demo.js' {
  declare module.exports: $Exports<'dagre-d3/dist/demo/demo'>;
}
declare module 'dagre-d3/dist/demo/tipsy.js' {
  declare module.exports: $Exports<'dagre-d3/dist/demo/tipsy'>;
}
declare module 'dagre-d3/index' {
  declare module.exports: $Exports<'dagre-d3'>;
}
declare module 'dagre-d3/index.js' {
  declare module.exports: $Exports<'dagre-d3'>;
}
declare module 'dagre-d3/karma.conf.js' {
  declare module.exports: $Exports<'dagre-d3/karma.conf'>;
}
declare module 'dagre-d3/karma.core.conf.js' {
  declare module.exports: $Exports<'dagre-d3/karma.core.conf'>;
}
declare module 'dagre-d3/lib/arrows.js' {
  declare module.exports: $Exports<'dagre-d3/lib/arrows'>;
}
declare module 'dagre-d3/lib/create-clusters.js' {
  declare module.exports: $Exports<'dagre-d3/lib/create-clusters'>;
}
declare module 'dagre-d3/lib/create-edge-labels.js' {
  declare module.exports: $Exports<'dagre-d3/lib/create-edge-labels'>;
}
declare module 'dagre-d3/lib/create-edge-paths.js' {
  declare module.exports: $Exports<'dagre-d3/lib/create-edge-paths'>;
}
declare module 'dagre-d3/lib/create-nodes.js' {
  declare module.exports: $Exports<'dagre-d3/lib/create-nodes'>;
}
declare module 'dagre-d3/lib/d3.js' {
  declare module.exports: $Exports<'dagre-d3/lib/d3'>;
}
declare module 'dagre-d3/lib/dagre.js' {
  declare module.exports: $Exports<'dagre-d3/lib/dagre'>;
}
declare module 'dagre-d3/lib/graphlib.js' {
  declare module.exports: $Exports<'dagre-d3/lib/graphlib'>;
}
declare module 'dagre-d3/lib/intersect/index' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect'>;
}
declare module 'dagre-d3/lib/intersect/index.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect'>;
}
declare module 'dagre-d3/lib/intersect/intersect-circle.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect/intersect-circle'>;
}
declare module 'dagre-d3/lib/intersect/intersect-ellipse.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect/intersect-ellipse'>;
}
declare module 'dagre-d3/lib/intersect/intersect-line.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect/intersect-line'>;
}
declare module 'dagre-d3/lib/intersect/intersect-node.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect/intersect-node'>;
}
declare module 'dagre-d3/lib/intersect/intersect-polygon.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect/intersect-polygon'>;
}
declare module 'dagre-d3/lib/intersect/intersect-rect.js' {
  declare module.exports: $Exports<'dagre-d3/lib/intersect/intersect-rect'>;
}
declare module 'dagre-d3/lib/label/add-html-label.js' {
  declare module.exports: $Exports<'dagre-d3/lib/label/add-html-label'>;
}
declare module 'dagre-d3/lib/label/add-label.js' {
  declare module.exports: $Exports<'dagre-d3/lib/label/add-label'>;
}
declare module 'dagre-d3/lib/label/add-svg-label.js' {
  declare module.exports: $Exports<'dagre-d3/lib/label/add-svg-label'>;
}
declare module 'dagre-d3/lib/label/add-text-label.js' {
  declare module.exports: $Exports<'dagre-d3/lib/label/add-text-label'>;
}
declare module 'dagre-d3/lib/lodash.js' {
  declare module.exports: $Exports<'dagre-d3/lib/lodash'>;
}
declare module 'dagre-d3/lib/position-clusters.js' {
  declare module.exports: $Exports<'dagre-d3/lib/position-clusters'>;
}
declare module 'dagre-d3/lib/position-edge-labels.js' {
  declare module.exports: $Exports<'dagre-d3/lib/position-edge-labels'>;
}
declare module 'dagre-d3/lib/position-nodes.js' {
  declare module.exports: $Exports<'dagre-d3/lib/position-nodes'>;
}
declare module 'dagre-d3/lib/render.js' {
  declare module.exports: $Exports<'dagre-d3/lib/render'>;
}
declare module 'dagre-d3/lib/shapes.js' {
  declare module.exports: $Exports<'dagre-d3/lib/shapes'>;
}
declare module 'dagre-d3/lib/util.js' {
  declare module.exports: $Exports<'dagre-d3/lib/util'>;
}
declare module 'dagre-d3/lib/version.js' {
  declare module.exports: $Exports<'dagre-d3/lib/version'>;
}
