// flow-typed signature: fbd6c00ed987af5a93e1967599ec1ab0
// flow-typed version: <<STUB>>/feather-icons-react_v^0.4.3/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'feather-icons-react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'feather-icons-react' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'feather-icons-react/build/IconInner' {
  declare module.exports: any;
}

declare module 'feather-icons-react/build' {
  declare module.exports: any;
}

// Filename aliases
declare module 'feather-icons-react/build/IconInner.js' {
  declare module.exports: $Exports<'feather-icons-react/build/IconInner'>;
}
declare module 'feather-icons-react/build/index' {
  declare module.exports: $Exports<'feather-icons-react/build'>;
}
declare module 'feather-icons-react/build/index.js' {
  declare module.exports: $Exports<'feather-icons-react/build'>;
}
