// flow-typed signature: dbc8c137aad004d90db980c1bd27feba
// flow-typed version: <<STUB>>/framer-motion_v^4.1.3/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'framer-motion'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'framer-motion' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'framer-motion/dist/es/animation/animate' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/animation-controls' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/use-animated-state' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/use-animation' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/utils/default-transitions' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/utils/easing' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/utils/is-animatable' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/utils/is-animation-controls' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/utils/is-keyframes-target' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/animation/utils/transitions' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimatePresence' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimatePresence/PresenceChild' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimatePresence/use-presence' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimateSharedLayout' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimateSharedLayout/types' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/batcher' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/crossfader' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/rotate' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/stack' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/LazyMotion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/components/MotionConfig' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/LayoutGroupContext' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/LazyContext' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/MotionConfigContext' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/MotionContext/create' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/MotionContext' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/MotionContext/utils' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/PresenceContext' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/context/SharedLayoutContext' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/events/event-info' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/events/use-dom-event' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/events/use-pointer-event' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/events/utils' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/drag/use-drag-controls' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/drag/use-drag' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/drag/utils/constraints' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/drag/utils/lock' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/drag/VisualElementDragControls' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/PanSession' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/use-focus-gesture' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/use-hover-gesture' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/use-pan-gesture' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/use-tap-gesture' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/utils/event-type' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/gestures/utils/is-node-or-child' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/animations' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/definitions' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/drag' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/gestures' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/layout/Animate' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/layout' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/layout/Measure' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/layout/utils' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/features/use-features' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/utils/is-forced-motion-value' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/utils/make-renderless-component' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/utils/use-motion-ref' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/utils/use-visual-element' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/utils/use-visual-state' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/motion/utils/valid-prop' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/create-visual-element' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/features-animation' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/features-max' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/motion-minimal' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/motion-proxy' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/projection/convert-to-relative' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/projection/default-scale-correctors' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/projection/measure' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/projection/relative-set' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/projection/scale-correction' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/projection/utils' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/use-render' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/camel-to-dash' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/create-config' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/css-variables-conversion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/filter-props' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/is-css-variable' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/is-svg-component' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/parse-dom-variant' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/utils/unit-conversion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/animatable-none' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/defaults' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/dimensions' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/find' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/get-as-type' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/number' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/test' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/type-auto' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/dom/value-types/type-int' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/config-motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/use-props' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/build-projection-transform' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/build-styles' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/build-transform' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/create-render-state' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/render' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/scrape-motion-values' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/utils/transform' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/html/visual-element' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/config-motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/lowercase-elements' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/use-props' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/build-attrs' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/camel-case-attrs' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/create-render-state' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/path' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/render' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/scrape-motion-values' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/utils/transform-origin' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/svg/visual-element' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/animation-state' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/animation' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/compare-by-depth' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/flat-tree' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/is-draggable' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/lifecycles' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/motion-values' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/projection' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/setters' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/state' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/types' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/render/utils/variants' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/array' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/each-axis' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/geometry/delta-apply' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/geometry/delta-calc' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/geometry' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/is-browser' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/is-numerical-string' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/is-ref-object' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/noop' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/resolve-value' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/shallow-compare' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/subscription-manager' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/time-conversion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/transform' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/use-constant' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/use-cycle' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/use-force-update' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/use-isomorphic-effect' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/use-reduced-motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/utils/use-unmount-effect' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/scroll/use-element-scroll' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/scroll/use-viewport-scroll' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/scroll/utils' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-combine-values' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-inverted-scale' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-motion-template' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-motion-value' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-on-change' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-spring' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-transform' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/use-velocity' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/utils/is-motion-value' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/es/value/utils/resolve-motion-value' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/framer-motion.cjs' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/framer-motion.dev' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/framer-motion' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/size-rollup-dom-animation' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/size-rollup-dom-max' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/size-rollup-m' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/size-webpack-dom-animation' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/size-webpack-dom-max' {
  declare module.exports: any;
}

declare module 'framer-motion/dist/size-webpack-m' {
  declare module.exports: any;
}

// Filename aliases
declare module 'framer-motion/dist/es/animation/animate.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/animate'>;
}
declare module 'framer-motion/dist/es/animation/animation-controls.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/animation-controls'>;
}
declare module 'framer-motion/dist/es/animation/use-animated-state.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/use-animated-state'>;
}
declare module 'framer-motion/dist/es/animation/use-animation.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/use-animation'>;
}
declare module 'framer-motion/dist/es/animation/utils/default-transitions.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/utils/default-transitions'>;
}
declare module 'framer-motion/dist/es/animation/utils/easing.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/utils/easing'>;
}
declare module 'framer-motion/dist/es/animation/utils/is-animatable.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/utils/is-animatable'>;
}
declare module 'framer-motion/dist/es/animation/utils/is-animation-controls.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/utils/is-animation-controls'>;
}
declare module 'framer-motion/dist/es/animation/utils/is-keyframes-target.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/utils/is-keyframes-target'>;
}
declare module 'framer-motion/dist/es/animation/utils/transitions.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/animation/utils/transitions'>;
}
declare module 'framer-motion/dist/es/components/AnimatePresence/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimatePresence'>;
}
declare module 'framer-motion/dist/es/components/AnimatePresence/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimatePresence'>;
}
declare module 'framer-motion/dist/es/components/AnimatePresence/PresenceChild.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimatePresence/PresenceChild'>;
}
declare module 'framer-motion/dist/es/components/AnimatePresence/use-presence.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimatePresence/use-presence'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/types.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout/types'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/batcher.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout/utils/batcher'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/crossfader.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout/utils/crossfader'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/rotate.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout/utils/rotate'>;
}
declare module 'framer-motion/dist/es/components/AnimateSharedLayout/utils/stack.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/AnimateSharedLayout/utils/stack'>;
}
declare module 'framer-motion/dist/es/components/LazyMotion/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/LazyMotion'>;
}
declare module 'framer-motion/dist/es/components/LazyMotion/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/LazyMotion'>;
}
declare module 'framer-motion/dist/es/components/MotionConfig/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/MotionConfig'>;
}
declare module 'framer-motion/dist/es/components/MotionConfig/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/components/MotionConfig'>;
}
declare module 'framer-motion/dist/es/context/LayoutGroupContext.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/LayoutGroupContext'>;
}
declare module 'framer-motion/dist/es/context/LazyContext.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/LazyContext'>;
}
declare module 'framer-motion/dist/es/context/MotionConfigContext.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/MotionConfigContext'>;
}
declare module 'framer-motion/dist/es/context/MotionContext/create.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/MotionContext/create'>;
}
declare module 'framer-motion/dist/es/context/MotionContext/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/MotionContext'>;
}
declare module 'framer-motion/dist/es/context/MotionContext/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/MotionContext'>;
}
declare module 'framer-motion/dist/es/context/MotionContext/utils.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/MotionContext/utils'>;
}
declare module 'framer-motion/dist/es/context/PresenceContext.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/PresenceContext'>;
}
declare module 'framer-motion/dist/es/context/SharedLayoutContext.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/context/SharedLayoutContext'>;
}
declare module 'framer-motion/dist/es/events/event-info.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/events/event-info'>;
}
declare module 'framer-motion/dist/es/events/use-dom-event.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/events/use-dom-event'>;
}
declare module 'framer-motion/dist/es/events/use-pointer-event.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/events/use-pointer-event'>;
}
declare module 'framer-motion/dist/es/events/utils.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/events/utils'>;
}
declare module 'framer-motion/dist/es/gestures/drag/use-drag-controls.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/drag/use-drag-controls'>;
}
declare module 'framer-motion/dist/es/gestures/drag/use-drag.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/drag/use-drag'>;
}
declare module 'framer-motion/dist/es/gestures/drag/utils/constraints.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/drag/utils/constraints'>;
}
declare module 'framer-motion/dist/es/gestures/drag/utils/lock.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/drag/utils/lock'>;
}
declare module 'framer-motion/dist/es/gestures/drag/VisualElementDragControls.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/drag/VisualElementDragControls'>;
}
declare module 'framer-motion/dist/es/gestures/PanSession.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/PanSession'>;
}
declare module 'framer-motion/dist/es/gestures/use-focus-gesture.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/use-focus-gesture'>;
}
declare module 'framer-motion/dist/es/gestures/use-hover-gesture.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/use-hover-gesture'>;
}
declare module 'framer-motion/dist/es/gestures/use-pan-gesture.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/use-pan-gesture'>;
}
declare module 'framer-motion/dist/es/gestures/use-tap-gesture.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/use-tap-gesture'>;
}
declare module 'framer-motion/dist/es/gestures/utils/event-type.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/utils/event-type'>;
}
declare module 'framer-motion/dist/es/gestures/utils/is-node-or-child.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/gestures/utils/is-node-or-child'>;
}
declare module 'framer-motion/dist/es/index' {
  declare module.exports: $Exports<'framer-motion/dist/es'>;
}
declare module 'framer-motion/dist/es/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es'>;
}
declare module 'framer-motion/dist/es/motion/features/animations.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/animations'>;
}
declare module 'framer-motion/dist/es/motion/features/definitions.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/definitions'>;
}
declare module 'framer-motion/dist/es/motion/features/drag.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/drag'>;
}
declare module 'framer-motion/dist/es/motion/features/gestures.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/gestures'>;
}
declare module 'framer-motion/dist/es/motion/features/layout/Animate.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/layout/Animate'>;
}
declare module 'framer-motion/dist/es/motion/features/layout/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/layout'>;
}
declare module 'framer-motion/dist/es/motion/features/layout/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/layout'>;
}
declare module 'framer-motion/dist/es/motion/features/layout/Measure.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/layout/Measure'>;
}
declare module 'framer-motion/dist/es/motion/features/layout/utils.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/layout/utils'>;
}
declare module 'framer-motion/dist/es/motion/features/use-features.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/features/use-features'>;
}
declare module 'framer-motion/dist/es/motion/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion'>;
}
declare module 'framer-motion/dist/es/motion/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion'>;
}
declare module 'framer-motion/dist/es/motion/utils/is-forced-motion-value.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/utils/is-forced-motion-value'>;
}
declare module 'framer-motion/dist/es/motion/utils/make-renderless-component.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/utils/make-renderless-component'>;
}
declare module 'framer-motion/dist/es/motion/utils/use-motion-ref.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/utils/use-motion-ref'>;
}
declare module 'framer-motion/dist/es/motion/utils/use-visual-element.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/utils/use-visual-element'>;
}
declare module 'framer-motion/dist/es/motion/utils/use-visual-state.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/utils/use-visual-state'>;
}
declare module 'framer-motion/dist/es/motion/utils/valid-prop.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/motion/utils/valid-prop'>;
}
declare module 'framer-motion/dist/es/render/dom/create-visual-element.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/create-visual-element'>;
}
declare module 'framer-motion/dist/es/render/dom/features-animation.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/features-animation'>;
}
declare module 'framer-motion/dist/es/render/dom/features-max.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/features-max'>;
}
declare module 'framer-motion/dist/es/render/dom/motion-minimal.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/motion-minimal'>;
}
declare module 'framer-motion/dist/es/render/dom/motion-proxy.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/motion-proxy'>;
}
declare module 'framer-motion/dist/es/render/dom/motion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/motion'>;
}
declare module 'framer-motion/dist/es/render/dom/projection/convert-to-relative.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/projection/convert-to-relative'>;
}
declare module 'framer-motion/dist/es/render/dom/projection/default-scale-correctors.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/projection/default-scale-correctors'>;
}
declare module 'framer-motion/dist/es/render/dom/projection/measure.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/projection/measure'>;
}
declare module 'framer-motion/dist/es/render/dom/projection/relative-set.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/projection/relative-set'>;
}
declare module 'framer-motion/dist/es/render/dom/projection/scale-correction.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/projection/scale-correction'>;
}
declare module 'framer-motion/dist/es/render/dom/projection/utils.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/projection/utils'>;
}
declare module 'framer-motion/dist/es/render/dom/use-render.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/use-render'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/camel-to-dash.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/camel-to-dash'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/create-config.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/create-config'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/css-variables-conversion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/css-variables-conversion'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/filter-props.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/filter-props'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/is-css-variable.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/is-css-variable'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/is-svg-component.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/is-svg-component'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/parse-dom-variant.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/parse-dom-variant'>;
}
declare module 'framer-motion/dist/es/render/dom/utils/unit-conversion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/utils/unit-conversion'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/animatable-none.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/animatable-none'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/defaults.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/defaults'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/dimensions.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/dimensions'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/find.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/find'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/get-as-type.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/get-as-type'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/number.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/number'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/test.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/test'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/type-auto.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/type-auto'>;
}
declare module 'framer-motion/dist/es/render/dom/value-types/type-int.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/dom/value-types/type-int'>;
}
declare module 'framer-motion/dist/es/render/html/config-motion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/config-motion'>;
}
declare module 'framer-motion/dist/es/render/html/use-props.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/use-props'>;
}
declare module 'framer-motion/dist/es/render/html/utils/build-projection-transform.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/build-projection-transform'>;
}
declare module 'framer-motion/dist/es/render/html/utils/build-styles.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/build-styles'>;
}
declare module 'framer-motion/dist/es/render/html/utils/build-transform.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/build-transform'>;
}
declare module 'framer-motion/dist/es/render/html/utils/create-render-state.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/create-render-state'>;
}
declare module 'framer-motion/dist/es/render/html/utils/render.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/render'>;
}
declare module 'framer-motion/dist/es/render/html/utils/scrape-motion-values.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/scrape-motion-values'>;
}
declare module 'framer-motion/dist/es/render/html/utils/transform.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/utils/transform'>;
}
declare module 'framer-motion/dist/es/render/html/visual-element.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/html/visual-element'>;
}
declare module 'framer-motion/dist/es/render/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/render'>;
}
declare module 'framer-motion/dist/es/render/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render'>;
}
declare module 'framer-motion/dist/es/render/svg/config-motion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/config-motion'>;
}
declare module 'framer-motion/dist/es/render/svg/lowercase-elements.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/lowercase-elements'>;
}
declare module 'framer-motion/dist/es/render/svg/use-props.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/use-props'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/build-attrs.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/build-attrs'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/camel-case-attrs.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/camel-case-attrs'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/create-render-state.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/create-render-state'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/path.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/path'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/render.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/render'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/scrape-motion-values.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/scrape-motion-values'>;
}
declare module 'framer-motion/dist/es/render/svg/utils/transform-origin.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/utils/transform-origin'>;
}
declare module 'framer-motion/dist/es/render/svg/visual-element.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/svg/visual-element'>;
}
declare module 'framer-motion/dist/es/render/utils/animation-state.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/animation-state'>;
}
declare module 'framer-motion/dist/es/render/utils/animation.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/animation'>;
}
declare module 'framer-motion/dist/es/render/utils/compare-by-depth.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/compare-by-depth'>;
}
declare module 'framer-motion/dist/es/render/utils/flat-tree.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/flat-tree'>;
}
declare module 'framer-motion/dist/es/render/utils/is-draggable.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/is-draggable'>;
}
declare module 'framer-motion/dist/es/render/utils/lifecycles.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/lifecycles'>;
}
declare module 'framer-motion/dist/es/render/utils/motion-values.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/motion-values'>;
}
declare module 'framer-motion/dist/es/render/utils/projection.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/projection'>;
}
declare module 'framer-motion/dist/es/render/utils/setters.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/setters'>;
}
declare module 'framer-motion/dist/es/render/utils/state.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/state'>;
}
declare module 'framer-motion/dist/es/render/utils/types.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/types'>;
}
declare module 'framer-motion/dist/es/render/utils/variants.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/render/utils/variants'>;
}
declare module 'framer-motion/dist/es/utils/array.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/array'>;
}
declare module 'framer-motion/dist/es/utils/each-axis.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/each-axis'>;
}
declare module 'framer-motion/dist/es/utils/geometry/delta-apply.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/geometry/delta-apply'>;
}
declare module 'framer-motion/dist/es/utils/geometry/delta-calc.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/geometry/delta-calc'>;
}
declare module 'framer-motion/dist/es/utils/geometry/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/geometry'>;
}
declare module 'framer-motion/dist/es/utils/geometry/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/geometry'>;
}
declare module 'framer-motion/dist/es/utils/is-browser.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/is-browser'>;
}
declare module 'framer-motion/dist/es/utils/is-numerical-string.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/is-numerical-string'>;
}
declare module 'framer-motion/dist/es/utils/is-ref-object.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/is-ref-object'>;
}
declare module 'framer-motion/dist/es/utils/noop.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/noop'>;
}
declare module 'framer-motion/dist/es/utils/resolve-value.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/resolve-value'>;
}
declare module 'framer-motion/dist/es/utils/shallow-compare.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/shallow-compare'>;
}
declare module 'framer-motion/dist/es/utils/subscription-manager.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/subscription-manager'>;
}
declare module 'framer-motion/dist/es/utils/time-conversion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/time-conversion'>;
}
declare module 'framer-motion/dist/es/utils/transform.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/transform'>;
}
declare module 'framer-motion/dist/es/utils/use-constant.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/use-constant'>;
}
declare module 'framer-motion/dist/es/utils/use-cycle.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/use-cycle'>;
}
declare module 'framer-motion/dist/es/utils/use-force-update.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/use-force-update'>;
}
declare module 'framer-motion/dist/es/utils/use-isomorphic-effect.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/use-isomorphic-effect'>;
}
declare module 'framer-motion/dist/es/utils/use-reduced-motion.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/use-reduced-motion'>;
}
declare module 'framer-motion/dist/es/utils/use-unmount-effect.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/utils/use-unmount-effect'>;
}
declare module 'framer-motion/dist/es/value/index' {
  declare module.exports: $Exports<'framer-motion/dist/es/value'>;
}
declare module 'framer-motion/dist/es/value/index.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value'>;
}
declare module 'framer-motion/dist/es/value/scroll/use-element-scroll.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/scroll/use-element-scroll'>;
}
declare module 'framer-motion/dist/es/value/scroll/use-viewport-scroll.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/scroll/use-viewport-scroll'>;
}
declare module 'framer-motion/dist/es/value/scroll/utils.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/scroll/utils'>;
}
declare module 'framer-motion/dist/es/value/use-combine-values.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-combine-values'>;
}
declare module 'framer-motion/dist/es/value/use-inverted-scale.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-inverted-scale'>;
}
declare module 'framer-motion/dist/es/value/use-motion-template.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-motion-template'>;
}
declare module 'framer-motion/dist/es/value/use-motion-value.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-motion-value'>;
}
declare module 'framer-motion/dist/es/value/use-on-change.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-on-change'>;
}
declare module 'framer-motion/dist/es/value/use-spring.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-spring'>;
}
declare module 'framer-motion/dist/es/value/use-transform.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-transform'>;
}
declare module 'framer-motion/dist/es/value/use-velocity.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/use-velocity'>;
}
declare module 'framer-motion/dist/es/value/utils/is-motion-value.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/utils/is-motion-value'>;
}
declare module 'framer-motion/dist/es/value/utils/resolve-motion-value.js' {
  declare module.exports: $Exports<'framer-motion/dist/es/value/utils/resolve-motion-value'>;
}
declare module 'framer-motion/dist/framer-motion.cjs.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion.cjs'>;
}
declare module 'framer-motion/dist/framer-motion.dev.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion.dev'>;
}
declare module 'framer-motion/dist/framer-motion.js' {
  declare module.exports: $Exports<'framer-motion/dist/framer-motion'>;
}
declare module 'framer-motion/dist/size-rollup-dom-animation.js' {
  declare module.exports: $Exports<'framer-motion/dist/size-rollup-dom-animation'>;
}
declare module 'framer-motion/dist/size-rollup-dom-max.js' {
  declare module.exports: $Exports<'framer-motion/dist/size-rollup-dom-max'>;
}
declare module 'framer-motion/dist/size-rollup-m.js' {
  declare module.exports: $Exports<'framer-motion/dist/size-rollup-m'>;
}
declare module 'framer-motion/dist/size-webpack-dom-animation.js' {
  declare module.exports: $Exports<'framer-motion/dist/size-webpack-dom-animation'>;
}
declare module 'framer-motion/dist/size-webpack-dom-max.js' {
  declare module.exports: $Exports<'framer-motion/dist/size-webpack-dom-max'>;
}
declare module 'framer-motion/dist/size-webpack-m.js' {
  declare module.exports: $Exports<'framer-motion/dist/size-webpack-m'>;
}
