// flow-typed signature: fd509ac831eb113a026d189c1b5f99ae
// flow-typed version: <<STUB>>/pathfinding_v^0.4.18/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pathfinding'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pathfinding' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'pathfinding/benchmark/benchmark' {
  declare module.exports: any;
}

declare module 'pathfinding/benchmark/parse_map' {
  declare module.exports: any;
}

declare module 'pathfinding/benchmark/parse_scen' {
  declare module.exports: any;
}

declare module 'pathfinding/benchmark/test_cases' {
  declare module.exports: any;
}

declare module 'pathfinding/gulpfile' {
  declare module.exports: any;
}

declare module 'pathfinding/src/core/DiagonalMovement' {
  declare module.exports: any;
}

declare module 'pathfinding/src/core/Grid' {
  declare module.exports: any;
}

declare module 'pathfinding/src/core/Heuristic' {
  declare module.exports: any;
}

declare module 'pathfinding/src/core/Node' {
  declare module.exports: any;
}

declare module 'pathfinding/src/core/Util' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/AStarFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/BestFirstFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/BiAStarFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/BiBestFirstFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/BiBreadthFirstFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/BiDijkstraFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/BreadthFirstFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/DijkstraFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/IDAStarFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/JPFAlwaysMoveDiagonally' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/JPFMoveDiagonallyIfAtMostOneObstacle' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/JPFMoveDiagonallyIfNoObstacles' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/JPFNeverMoveDiagonally' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/JumpPointFinder' {
  declare module.exports: any;
}

declare module 'pathfinding/src/finders/JumpPointFinderBase' {
  declare module.exports: any;
}

declare module 'pathfinding/src/PathFinding' {
  declare module.exports: any;
}

declare module 'pathfinding/test/Grid' {
  declare module.exports: any;
}

declare module 'pathfinding/test/PathTest' {
  declare module.exports: any;
}

declare module 'pathfinding/test/PathTestScenarios' {
  declare module.exports: any;
}

declare module 'pathfinding/test/Util' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/js/controller' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/js/main' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/js/panel' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/js/view' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/async.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/es5-shim.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/jquery-1.7.2.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/pathfinding-browser.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/raphael-min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/state-machine.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/ui/jquery.ui.accordion.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/ui/jquery.ui.core.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/ui/jquery.ui.draggable.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/ui/jquery.ui.mouse.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/ui/jquery.ui.slider.min' {
  declare module.exports: any;
}

declare module 'pathfinding/visual/lib/ui/jquery.ui.widget.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'pathfinding/benchmark/benchmark.js' {
  declare module.exports: $Exports<'pathfinding/benchmark/benchmark'>;
}
declare module 'pathfinding/benchmark/parse_map.js' {
  declare module.exports: $Exports<'pathfinding/benchmark/parse_map'>;
}
declare module 'pathfinding/benchmark/parse_scen.js' {
  declare module.exports: $Exports<'pathfinding/benchmark/parse_scen'>;
}
declare module 'pathfinding/benchmark/test_cases.js' {
  declare module.exports: $Exports<'pathfinding/benchmark/test_cases'>;
}
declare module 'pathfinding/gulpfile.js' {
  declare module.exports: $Exports<'pathfinding/gulpfile'>;
}
declare module 'pathfinding/index' {
  declare module.exports: $Exports<'pathfinding'>;
}
declare module 'pathfinding/index.js' {
  declare module.exports: $Exports<'pathfinding'>;
}
declare module 'pathfinding/src/core/DiagonalMovement.js' {
  declare module.exports: $Exports<'pathfinding/src/core/DiagonalMovement'>;
}
declare module 'pathfinding/src/core/Grid.js' {
  declare module.exports: $Exports<'pathfinding/src/core/Grid'>;
}
declare module 'pathfinding/src/core/Heuristic.js' {
  declare module.exports: $Exports<'pathfinding/src/core/Heuristic'>;
}
declare module 'pathfinding/src/core/Node.js' {
  declare module.exports: $Exports<'pathfinding/src/core/Node'>;
}
declare module 'pathfinding/src/core/Util.js' {
  declare module.exports: $Exports<'pathfinding/src/core/Util'>;
}
declare module 'pathfinding/src/finders/AStarFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/AStarFinder'>;
}
declare module 'pathfinding/src/finders/BestFirstFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/BestFirstFinder'>;
}
declare module 'pathfinding/src/finders/BiAStarFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/BiAStarFinder'>;
}
declare module 'pathfinding/src/finders/BiBestFirstFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/BiBestFirstFinder'>;
}
declare module 'pathfinding/src/finders/BiBreadthFirstFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/BiBreadthFirstFinder'>;
}
declare module 'pathfinding/src/finders/BiDijkstraFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/BiDijkstraFinder'>;
}
declare module 'pathfinding/src/finders/BreadthFirstFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/BreadthFirstFinder'>;
}
declare module 'pathfinding/src/finders/DijkstraFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/DijkstraFinder'>;
}
declare module 'pathfinding/src/finders/IDAStarFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/IDAStarFinder'>;
}
declare module 'pathfinding/src/finders/JPFAlwaysMoveDiagonally.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/JPFAlwaysMoveDiagonally'>;
}
declare module 'pathfinding/src/finders/JPFMoveDiagonallyIfAtMostOneObstacle.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/JPFMoveDiagonallyIfAtMostOneObstacle'>;
}
declare module 'pathfinding/src/finders/JPFMoveDiagonallyIfNoObstacles.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/JPFMoveDiagonallyIfNoObstacles'>;
}
declare module 'pathfinding/src/finders/JPFNeverMoveDiagonally.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/JPFNeverMoveDiagonally'>;
}
declare module 'pathfinding/src/finders/JumpPointFinder.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/JumpPointFinder'>;
}
declare module 'pathfinding/src/finders/JumpPointFinderBase.js' {
  declare module.exports: $Exports<'pathfinding/src/finders/JumpPointFinderBase'>;
}
declare module 'pathfinding/src/PathFinding.js' {
  declare module.exports: $Exports<'pathfinding/src/PathFinding'>;
}
declare module 'pathfinding/test/Grid.js' {
  declare module.exports: $Exports<'pathfinding/test/Grid'>;
}
declare module 'pathfinding/test/PathTest.js' {
  declare module.exports: $Exports<'pathfinding/test/PathTest'>;
}
declare module 'pathfinding/test/PathTestScenarios.js' {
  declare module.exports: $Exports<'pathfinding/test/PathTestScenarios'>;
}
declare module 'pathfinding/test/Util.js' {
  declare module.exports: $Exports<'pathfinding/test/Util'>;
}
declare module 'pathfinding/visual/js/controller.js' {
  declare module.exports: $Exports<'pathfinding/visual/js/controller'>;
}
declare module 'pathfinding/visual/js/main.js' {
  declare module.exports: $Exports<'pathfinding/visual/js/main'>;
}
declare module 'pathfinding/visual/js/panel.js' {
  declare module.exports: $Exports<'pathfinding/visual/js/panel'>;
}
declare module 'pathfinding/visual/js/view.js' {
  declare module.exports: $Exports<'pathfinding/visual/js/view'>;
}
declare module 'pathfinding/visual/lib/async.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/async.min'>;
}
declare module 'pathfinding/visual/lib/es5-shim.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/es5-shim.min'>;
}
declare module 'pathfinding/visual/lib/jquery-1.7.2.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/jquery-1.7.2.min'>;
}
declare module 'pathfinding/visual/lib/pathfinding-browser.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/pathfinding-browser.min'>;
}
declare module 'pathfinding/visual/lib/raphael-min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/raphael-min'>;
}
declare module 'pathfinding/visual/lib/state-machine.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/state-machine.min'>;
}
declare module 'pathfinding/visual/lib/ui/jquery.ui.accordion.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/ui/jquery.ui.accordion.min'>;
}
declare module 'pathfinding/visual/lib/ui/jquery.ui.core.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/ui/jquery.ui.core.min'>;
}
declare module 'pathfinding/visual/lib/ui/jquery.ui.draggable.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/ui/jquery.ui.draggable.min'>;
}
declare module 'pathfinding/visual/lib/ui/jquery.ui.mouse.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/ui/jquery.ui.mouse.min'>;
}
declare module 'pathfinding/visual/lib/ui/jquery.ui.slider.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/ui/jquery.ui.slider.min'>;
}
declare module 'pathfinding/visual/lib/ui/jquery.ui.widget.min.js' {
  declare module.exports: $Exports<'pathfinding/visual/lib/ui/jquery.ui.widget.min'>;
}
