// flow-typed signature: 9c4593ee2f6e859250bee9a207ac9537
// flow-typed version: <<STUB>>/react-dropdown_v^1.6.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-dropdown'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-dropdown' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-dropdown/dist' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-dropdown/dist/index' {
  declare module.exports: $Exports<'react-dropdown/dist'>;
}
declare module 'react-dropdown/dist/index.js' {
  declare module.exports: $Exports<'react-dropdown/dist'>;
}
