// flow-typed signature: d634861063e40a5a262587d49fc33b35
// flow-typed version: <<STUB>>/react-highlight.js_v^1.0.7/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-highlight.js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-highlight.js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-highlight.js/dist/main' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-highlight.js/dist/main.js' {
  declare module.exports: $Exports<'react-highlight.js/dist/main'>;
}
