// flow-typed signature: a257ec056d3b842513f173ec6e450556
// flow-typed version: <<STUB>>/react-organizational-chart_v^1.0.2/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-organizational-chart'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-organizational-chart' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-organizational-chart/dist' {
  declare module.exports: any;
}

declare module 'react-organizational-chart/dist/index.modern' {
  declare module.exports: any;
}

declare module 'react-organizational-chart/dist/index.module' {
  declare module.exports: any;
}

declare module 'react-organizational-chart/dist/index.umd' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-organizational-chart/dist/index' {
  declare module.exports: $Exports<'react-organizational-chart/dist'>;
}
declare module 'react-organizational-chart/dist/index.js' {
  declare module.exports: $Exports<'react-organizational-chart/dist'>;
}
declare module 'react-organizational-chart/dist/index.modern.js' {
  declare module.exports: $Exports<'react-organizational-chart/dist/index.modern'>;
}
declare module 'react-organizational-chart/dist/index.module.js' {
  declare module.exports: $Exports<'react-organizational-chart/dist/index.module'>;
}
declare module 'react-organizational-chart/dist/index.umd.js' {
  declare module.exports: $Exports<'react-organizational-chart/dist/index.umd'>;
}
