// flow-typed signature: d3c2fae93777614c4aa52f092b7d5348
// flow-typed version: <<STUB>>/unescape-js_v^1.1.4/flow_v0.132.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'unescape-js'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'unescape-js' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'unescape-js/dist' {
  declare module.exports: any;
}

declare module 'unescape-js/src' {
  declare module.exports: any;
}

declare module 'unescape-js/test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'unescape-js/dist/index' {
  declare module.exports: $Exports<'unescape-js/dist'>;
}
declare module 'unescape-js/dist/index.js' {
  declare module.exports: $Exports<'unescape-js/dist'>;
}
declare module 'unescape-js/src/index' {
  declare module.exports: $Exports<'unescape-js/src'>;
}
declare module 'unescape-js/src/index.js' {
  declare module.exports: $Exports<'unescape-js/src'>;
}
declare module 'unescape-js/test/index' {
  declare module.exports: $Exports<'unescape-js/test'>;
}
declare module 'unescape-js/test/index.js' {
  declare module.exports: $Exports<'unescape-js/test'>;
}
