name: frinx-api package

on:
  push:
    tags:
      - api-*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PRIVATE_GH_TOKEN: ${{secrets.PACKAGE_TOKEN}}
      PRIVATE_NPM_TOKEN: ${{secrets.PUBLISH_TOKEN}}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      - run: cp .npmrc.ci .npmrc
      - run: npm ci
      - run: npm run build:api
      - run: cd packages/frinx-api && npm publish
