name: frinx-api package

on:
  push:
    tags:
      - api-*

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      YARN_NPM_AUTH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
          registry-url: https://registry.npmjs.org/
          always-auth: true
      - run: YARN_NPM_AUTH_TOKEN=${{ secrets.PACKAGE_TOKEN }} yarn install --immutable
      - run: yarn run build:api
      - run: YARN_NPM_AUTH_TOKEN=${{secrets.PUBLISH_TOKEN}} cd packages/frinx-api && yarn npm publish --access public
