name: Bump and publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: "Publish to npm"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Set up Node.js
        uses: actions/setup-node@master
        with:
          node-version: 12
      - name: install babel
        run: |
          npm install --save-dev @babel/core @babel/cli
      - name: npm run transpile
        run: |
          npm run transpile
      - name: copy files
        run: |
          mkdir build
          cp -r lib/ package.json package-lock.json README.md build
      - name: bump version and publish
        run: |
          cd build
          ls -l
          npm version patch
          npm config set //registry.npmjs.org/:_authToken=$NPM_AUTH_TOKEN
          npm publish --access public
        env:
          CI: true 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }} 
  bump-version:
    name: "Bump version"
    needs: publish
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout source code"
        uses: "actions/checkout@v2"
        with:
          ref: ${{ github.ref }}
      - name: "cat package.json"
        run: cat ./package.json
      - name: "Setup Node.js"
        uses: "actions/setup-node@v1"
        with:
          node-version: 12
      - name: "Automated Version Bump"
        uses: "FRINXio/gh-action-bump-version@master"
        with:
          tag-prefix: ''
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: "cat package.json"
        run: cat ./package.json 
