name: Docker

on:
  push:
    branches:
      - master    # Publish 'master' as Docker 'latest' image.
    tags:
      - v*        # Publish `v1.2.3` tags as releases.

env:
  # TODO: Change variable to your image's name.
  IMAGE_NAME: frinx/uniconfig-ui

jobs:
  push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Build image
        run: docker build . --file Dockerfile --tag $IMAGE_NAME

      - name: Log into Docker Hub
        run: echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} --password-stdin

      - name: Push image
        run: |
          IMAGE_ID=$IMAGE_NAME

          # Change all uppercase to lowercase
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')

          # Strip git ref prefix from version
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')

          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')

          # Use Docker `latest` tag convention
          [ "$VERSION" == "master" ] && VERSION=latest

          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION

          docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
          docker push $IMAGE_ID:$VERSION

          # Add latest tag if we are on master and github.ref points to a tag
          if [[ "${{ github.ref }}" == "refs/tags/"* ]]; then
            MASTER=$(git show-ref --hash origin/master)
            echo "master: $MASTER"
            HEAD=$(git rev-parse HEAD)
            echo "head: $HEAD"
            echo "github.ref ${{ github.ref }}"
            if [[ $MASTER == $HEAD ]]; then
              VERSION=latest
              echo VERSION=$VERSION
              docker tag $IMAGE_NAME $IMAGE_ID:$VERSION
              docker push $IMAGE_ID:$VERSION
            fi
          fi
