name: Integration tests

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      PRIVATE_GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      PRIVATE_NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Use CI yarnrc
        run: cp .yarnrc.ci.yml .yarnrc.yml
      - name: Copy yarn.lock file
        run: cp yarn.lock yarn.lock.orig
      - name: Create directory
        run: mkdir build-client
      - name: Prepare env variable
        run: cp ./packages/frinx-frontend-server/.env.example ./packages/frinx-frontend-server/.env
      - name: Cypress tests
        uses: cypress-io/github-action@v4
        with:
          project: ./cypress
          start: yarn dev
          wait-on: 'http://localhost:3000'
