name: Integration tests

on:
  pull_request:
    branches:
      - main
jobs:
  integration-tests:
    runs-on: ubuntu-latest
    env:
      PRIVATE_GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      PRIVATE_NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Use CI yarnrc
        run: cp .yarnrc.ci.yml .yarnrc.yml
      - name: Copy yarn.lock file
        run: cp yarn.lock yarn.lock.orig
      - name: Install dependencies
        run: yarn install --immutable
      - name: Cypress tests
        uses: cypress-io/github-action@v4
