name: PR check

on:
  pull_request:
    branches:
      - main

jobs:
  pr-check:
    runs-on: ubuntu-latest
    container: node:14-alpine
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v2
      - name: Copy yarn.lock file
        run: cp yarn.lock yarn.lock.orig
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check code formatting
        run: yarn run formatter:check
      - name: Check for dependencies version in monorepo
        run: yarn run dedubcheck
      - name: Build dependencies
        run: yarn run build:api
      - name: Run eslint check in Dashboard
        run: yarn run lint:dashboard
      - name: Run eslint check in Workflow Builder
        run: yarn run lint:workflow-builder
      - name: Run eslint check in Frinx api
        run: yarn run lint:api
      - name: Check types in Workflow Builder
        run: yarn run type-check:workflow-builder
      - name: Run eslint check in Inventory client
        run: yarn run lint:inventory
      - name: Check types in Inventory client
        run: yarn run type-check:inventory
      - name: Check types in Frinx api
        run: yarn run type-check:api
