name: PR check

on:
  pull_request:
    branches:
      - main
      - story-new-graphql-proxy
# Needed for nx-set-shas when run on the main branch
permissions:
  actions: read
  contents: read
jobs:
  pr-check:
    runs-on: ubuntu-latest
    container: node:18.18.0-alpine
    env:
      PRIVATE_GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      PRIVATE_NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use CI npmrc
        run: cp .npmrc.ci .npmrc
      - name: Install dependencies
        run: npm ci

      - uses: nrwl/nx-set-shas@v3
      # This line is needed for nx affected to work when CI is running on a PR
      - run: git branch --track main origin/main

      - run: npx nx-cloud record -- nx format:check
      - run: npx nx affected -t lint test build e2e-ci

      - name: Check code formatting
        run: npm run formatter:check
      - name: Run PR check
        run: npm run pr
