name: PR check

on:
  pull_request:
    branches:
      - main
jobs:
  pr-check:
    runs-on: ubuntu-latest
    container: node:16.19.1-alpine
    env:
      PRIVATE_GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      PRIVATE_NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v3
      - name: Use CI yarnrc
        run: cp .yarnrc.ci.yml .yarnrc.yml
      - name: Copy yarn.lock file
        run: cp yarn.lock yarn.lock.orig
      - name: Install dependencies
        run: yarn install --immutable
      - name: Check code formatting
        run: yarn run formatter:check
      - name: Build dependencies
        run: yarn run build:api
      - name: Run PR check
        run: yarn run pr
