name: PR check

on:
  pull_request:
    branches:
      - main
jobs:
  pr-check:
    runs-on: ubuntu-latest
    container: node:19.9.0-alpine
    env:
      PRIVATE_GH_TOKEN: ${{ secrets.PACKAGE_TOKEN }}
      PRIVATE_NPM_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
      TURBO_TOKEN: ${{ secrets.TURBO_TOKEN }}
      TURBO_TEAM: ${{ secrets.TURBO_TEAM }}
    steps:
      - name: Checkout repository code
        uses: actions/checkout@v4
      - name: Use CI npmrc
        run: cp .npmrc.ci .npmrc
      - name: Install dependencies
        run: npm ci
      - name: Check code formatting
        run: npm run formatter:check
      - name: Build
        run: npm run build
      - name: Run PR check
        run: npm run pr
